baseURL = 'https://matekdev.github.io/'
languageCode = 'en-us'
title = 'Matthew Zegar'
pluralizeListTitles = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.highlight]
            style = 'monokai'

[menu]
    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        url = "/blog/"
        weight = 2
