baseURL = 'https://matekdev.github.io/'
languageCode = 'en-us'
title = 'Matthew Zegar'

[menu]
    [[menu.main]]
        name = "Projects"
        url = "/projects/"
        weight = 1
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 2
